task1 is success!
task2 is fail!
[ERROR] package.Exception : message¡¦
at ¡¦
task3 is success!